cache:
    - ccache
    - directories:
        - $HOME/brew-cache
notifications:
    email: false
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env:
        - DOCKER_OS=ubuntu:14.04;ubuntu:16.04;ubuntu:latest
    - os: osx
      osx_image: xcode7.3
      env:
        - HOMEBREW_CACHE=$HOME/brew-cache
before_install:
    - ./.travis/travis_install.sh
script:
    - echo ${DOCKER_OS}
    - ./.travis/travis_build.sh
    - ./test/testrunner.sh
after_success:
    - ./.travis/travis_deploy.sh
